In [1]:
import pandas as pd
import numpy as np

In [2]:
listings_ams = pd.read_csv('../data/cleaned/listings_ams.csv', index_col=0)

In [3]:
listings_ams.shape

(6809, 33)

In [4]:
pd.options.display.max_columns = None
display(listings_ams)

,name,description,neighborhood_overview,host_id,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,Somewhere Else,Highlights<br />*Located only 5 minutes from C...,NaN,2594559,NaN,within a day,87%,96%,f,t,Westerpark,52.391140,4.888460,Private room in boat,Private room,2,1.5 baths,1.0,1.0,"[""Bed linens"", ""Dishes and silverware"", ""Hange...",$100.00,2,30,t,248,4.85,4.88,4.83,4.93,4.90,4.78,4.72,f
1,Quiet Garden View Room & Super Fast Wi-Fi,Quiet Garden View Room & Super Fast Wi-Fi<br /...,"Indische Buurt (""Indies Neighborhood"") is a ne...",3159,"Upon arriving in Amsterdam, one can imagine as...",within an hour,100%,100%,t,t,Oostelijk Havengebied - Indische Buurt,52.364350,4.943580,Private room in rental unit,Private room,2,1.5 shared baths,1.0,2.0,"[""Books and reading material"", ""Smoke alarm"", ...",$59.00,3,28,t,314,4.89,4.93,4.99,4.97,4.98,4.69,4.81,f
2,Studio with private bathroom in the centre 1,17th century Dutch townhouse in the heart of t...,Located just in between famous central canals....,59484,+ (Phone number hidden by Airbnb),within an hour,100%,98%,f,t,Centrum-Oost,52.364070,4.893930,Private room in townhouse,Private room,2,1 private bath,1.0,1.0,"[""Smoke alarm"", ""Bed linens"", ""Hangers"", ""Wifi...",$106.00,1,365,t,339,4.44,4.69,4.79,4.63,4.62,4.87,4.49,t
3,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,"Central, quiet, safe, clean and beautiful.",97647,"Marjan works in ""eye"" the dutch filmmuseum, an...",within an hour,100%,100%,t,t,Centrum-West,52.387610,4.891880,Private room in houseboat,Private room,2,1.5 baths,1.0,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",$140.00,2,356,t,243,4.94,4.93,4.95,4.95,4.92,4.89,4.79,t
4,Comfortable double room,<b>The space</b><br />In a monumental house ri...,"Flower market , Leidseplein , Rembrantsplein",124245,Hi,within a few hours,100%,100%,t,t,Centrum-West,52.367750,4.890920,Private room in rental unit,Private room,2,1 shared bath,1.0,1.0,"[""Smoke alarm"", ""Bed linens"", ""Lock on bedroom...",$75.00,2,1825,t,454,4.88,4.93,4.89,4.95,4.94,4.97,4.83,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6804,Romantic Houseboat in the center,Located in the center everything can be walked...,"Redlight district, Waterlooplein market, every...",4184910,"Hello,\r\n\r\nMy name is Lydia and live in Ams...",within a day,80%,88%,t,t,Centrum-Oost,52.368637,4.899096,Private room in boat,Private room,2,1 private bath,1.0,1.0,"[""Smoke alarm"", ""Fire extinguisher"", ""Waterfro...",$165.00,1,1125,t,343,4.76,4.83,4.64,4.86,4.71,4.93,4.59,f
6805,mediterranean ambiance appartment,<b>The space</b><br />If you love Mediterranea...,NaN,4215174,It' s been already more than 20 years that I l...,within a day,100%,0%,f,t,De Baarsjes - Oud-West,52.368840,4.861270,Entire rental unit,Entire home/apt,4,1 bath,2.0,2.0,"[""Kitchen"", ""Wifi"", ""TV"", ""Oven"", ""Hot water"",...",$150.00,4,14,t,18,4.83,4.83,4.67,4.94,5.00,4.67,4.50,f
6806,Charlie + Coco's Apartment,Charlie + Coco are looking forward to welcome ...,NaN,1657181,.,within an hour,100%,83%,f,t,De Pijp - Rivierenbuurt,52.352050,4.902670,Entire rental unit,Entire home/apt,3,1 bath,2.0,2.0,"[""Smoke alarm"", ""Patio or balcony"", ""Coffee ma...",$160.00,3,1124,t,97,4.57,4.66,4.41,4.68,4.71,4.76,4.41,f
6807,Sleeping in a unique ship in the center of A'dam!,Thank you for finding me. I offer you an uniqu...,The Keizerinn BnB is located in one of the old...,4221960,Welcome on my boat!\n\nI'm offering you a won...,within an hour,100%,99%,t,t,Centrum-Oost,52.364760,4.909250,Private room in boat,Private room,2,1 private bath,1.0,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",$125.00,1,30,t,1060,4.93,4.92,4.95,4.97,4.97,4.92,4.81,f
6808,Sunny & Bright 3 bed apt with Roof terrace,"This sunny, spacious, trendy and clean 123m2 ...",NaN,4239235,"A bit about me, I love working hard and fillin...",NaN,NaN,50%,f,t,De Pijp - Rivierenbuurt,52.347250,4.893410,Entire rental unit,Entire home/apt,6,1.5 baths,2.0,2.0,"[""Smoke alarm"", ""BBQ grill"", ""Outdoor dining a...",$249.00,4,21,t,17,4.94,5.00,4.94,5.00,5.00,4.76,4.76,f

In [5]:
listings_ams.columns

Index(['name', 'description', 'neighborhood_overview', 'host_id', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_identity_verified', 'neighbourhood_cleansed',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'has_availability',
       'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable'],
      dtype='object')

In [6]:
listings_ams.dtypes

name                            object
description                     object
neighborhood_overview           object
host_id                          int64
host_about                      object
host_response_time              object
host_response_rate              object
host_acceptance_rate            object
host_is_superhost               object
host_identity_verified          object
neighbourhood_cleansed          object
latitude                       float64
longitude                      float64
property_type                   object
room_type                       object
accommodates                     int64
bathrooms_text                  object
bedrooms                       float64
beds                           float64
amenities                       object
price                           object
minimum_nights                   int64
maximum_nights                   int64
has_availability                object
number_of_reviews                int64
review_scores_rating           float64
review_scores_accuracy         float64
review_scores_cleanliness      float64
review_scores_checkin          float64
review_scores_communication    float64
review_scores_location         float64
review_scores_value            float64
instant_bookable                object
dtype: object

In [7]:
listings_ams['host_is_superhost'].unique()

array(['f', 't', nan], dtype=object)

In [8]:
listings_ams.isna().sum()

name                              0
description                       8
neighborhood_overview          2381
host_id                           0
host_about                     2787
host_response_time             2054
host_response_rate             2054
host_acceptance_rate            992
host_is_superhost                 4
host_identity_verified            0
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms_text                   13
bedrooms                        286
beds                             91
amenities                         0
price                             0
minimum_nights                    0
maximum_nights                    0
has_availability                  0
number_of_reviews                 0
review_scores_rating            648
review_scores_accuracy          652
review_scores_cleanliness       652
review_scores_checkin           652
review_scores_communication     652
review_scores_location          652
review_scores_value             652
instant_bookable                  0
dtype: int64

In [9]:
reviews=listings_ams.loc[:,['host_id','review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value']]
reviews.to_csv('../data/cleaned/reviews.csv')

In [ ]:
#Dealing with missing values
#deleting host_about column
listings_ams=listings_ams.drop(['host_about','neighborhood_overview','host_response_time',
                                'host_response_rate', 'review_scores_rating', 'review_scores_accuracy',
                                'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication',
                                'review_scores_location', 'review_scores_value', 'host_acceptance_rate',
                                'description'],axis=1)

In [ ]:
listings_ams.isna().sum()

In [ ]:
#Number of bedrooms is an important information for analysis. Therefore, I decided to delete the rows.
listings_ams=listings_ams[listings_ams['bedrooms'].notna()]

In [ ]:
listings_ams.isna().sum()

In [ ]:
#Number of bathrooms is an important information for analysis. Therefore, I decided to delete the rows.

listings_ams=listings_ams[listings_ams['bathrooms_text'].notna()]

In [ ]:
listings_ams.isna().sum()

In [ ]:
#Although the number of beds is important, accommodates indicate the max number of people that the property can host.
#Therefore, I decided to delete the column beds
listings_ams=listings_ams.drop(['beds'], axis=1)

In [ ]:
listings_ams.isna().sum()

In [ ]:
listings_ams.head()

In [ ]:
#Clean: remove '$' from price
def remove_symbol(x):
    x=x.replace('$','')
    return x


def remove_symbol_2(x):
    x=x.replace(',','')
    return x


listings_ams['price']=listings_ams['price'].apply(remove_symbol)
listings_ams['price']=listings_ams['price'].apply(remove_symbol_2)

In [ ]:
listings_ams['bathrooms_text'].unique()

In [ ]:
listings_ams.info()

In [ ]:
#Transform data type

#'bedrooms' - int
listings_ams['bedrooms'].astype(int)

In [ ]:
#'price' - int

listings_ams['price']=listings_ams['price'].astype(float)

In [ ]:
listings_ams.info()

In [ ]:
listings_ams.to_csv('../data/cleaned/listings_ams2.csv')

In [ ]:
pd.options.display.max_columns = None
display(listings_ams)

In [ ]:
listings_ams['amenities'][1]

In [ ]:
listings_ams['amenities'][2]

In [ ]:
listings_ams['amenities'][3]

In [ ]:
listings_ams.shape

In [ ]:
#Code for getting all the amenities listed in the listings_ams['amenities']


# unique_amenities = {}

# for entry in listings_ams["amenities"]:    
#     s = entry[1:-1]
#     l = [x.replace("\"", "").strip() for x in s.split(",")]
    
#     for amenity in l:
#         if amenity not in unique_amenities:
#             unique_amenities[amenity] = 1
#         else:
#             unique_amenities[amenity] += 1
            
            
# unique_amenities            

# top20_amenities = sorted(unique_amenities.items(), key=lambda x: x[1])[-20:]
# top20_amenities = [x[0] for x in top20_amenities]
# top20_amenities

In [ ]:
# amenities=pd.DataFrame.from_dict(unique_amenities.items())
# amenities=amenities.rename(columns={0:'Amenity',1:'Quantity'})
# amenities=amenities.sort_values(by=['Quantity'], ascending=False)
# amenities.tail(50)

In [ ]:
type(listings_ams['amenities'][3])


Smoke_Alarm median_price_1 
Essentials median_price_2
Wifi median_price_3

In [ ]:
def clean5 (l):
    l = l.split(",")
    l = ["TV" if "TV" in x else x for x in l]
    l = ["Sound System" if "sound system" in x else x for x in l]
    l = ["Shampoo" if "shampoo" in x else x for x in l]
    l = ["Shampoo" if "Shampoo" in x else x for x in l]
    l = ["Shower gel" if "soap" in x else x for x in l]
    l = ["Shower gel" if "Shower gel" in x else x for x in l]
    l = ["Conditioner" if "conditioner" in x else x for x in l]
    l = ["Conditioner" if "Conditioner" in x else x for x in l]
    l = ["Wifi" if "Wifi" in x else x for x in l]
    l = ["Wifi" if "Mbps" in x else x for x in l]
    l = ["Wifi" if "Mbps" in x else x for x in l]
    l = ["Stove" if "stove" in x else x for x in l]
    l = ["Oven" if "oven" in x else x for x in l]
    l = ["Refrigerator" if "refrigerator" in x else x for x in l]
    l = ["Wardrobe" if "wardrobe" in x else x for x in l]
    l = ["Closet" if "closet" in x else x for x in l]
    l = ["Paid parking" if "Paid parking" in x else x for x in l]
    l = ["High chair" if "high chair" in x else x for x in l]
    l = ["Coffee maker" if "Coffee maker" in x else x for x in l]
    l = ["Hot tub" if "hot tub" in x else x for x in l]
    l = ["Coffee maker" if "Nespresso" in x else x for x in l]
    l = ["Wardrobe" if "dresser" in x else x for x in l]
    l = ["Kitchen" if "kitchen" in x else x for x in l]
    l = ["Kitchen" if "Kitchen" in x else x for x in l]
    l = ["Fireplace" if "fireplace" in x else x for x in l]
    l = ["Coffee" if "pour-over coffee" in x else x for x in l]
    l = ["Bed linen" if "Bed linens" in x else x for x in l]
    l = ["Coffee" if "Coffee" in x else x for x in l]
    l = ["Crib" if "Crib" in x else x for x in l]
    l = ["Bike" if "Bikes" in x else x for x in l]
    l = ["Bike" if "bike" in x else x for x in l]
    l = ["Elevator" if "Lift" in x else x for x in l]
    l = ["Netflix" if "Netflix" in x else x for x in l]
    l = ["Central heating" if "Heating" in x else x for x in l]
    l = ["Free washer" if "Free washer" in x else x for x in l]
    l = ["Free dryer" if "Free dryer" in x else x for x in l]
    l = ["Children books and toys" if "books and toys" in x else x for x in l]
    l = ["Wardrobe" if "Clothing storage" in x else x for x in l]
    l = ["Fireplace" if "Fire pit" in x else x for x in l]
    l = ["Backyard" if "backyard" in x else x for x in l]
    l = ["Backyard" if "Backyard" in x else x for x in l]
    l = ["Backyard" if "backyard" in x else x for x in l]
    l = ["Parking" if "parking" in x else x for x in l]
    l = ["Parking" if "Parking" in x else x for x in l]
    l = ["Air conditioning" if "air conditioning" in x else x for x in l]
    l = ["Air conditioning" if "Air conditioning" in x else x for x in l]

    return l

In [ ]:
listings_ams['amenities']=listings_ams['amenities'].apply(clean5)

In [ ]:
listings_ams['amenities'][3]

In [ ]:
pd.options.display.max_columns = None
display(listings_ams)

In [ ]:
# unique_amenities2 = {}

# for entry in listings_ams["amenities"]:    
# #     s = entry[1:-1]
# #     l = [x.replace("\"", "").strip() for x in s.split(",")]
    
#     for amenity in entry:
#         if amenity not in unique_amenities2:
#             unique_amenities2[amenity] = 1
#         else:
#             unique_amenities2[amenity] += 1

In [ ]:
# amenities2=pd.DataFrame.from_dict(unique_amenities2.items())
# amenities2=amenities2.rename(columns={0:'Amenity',1:'Quantity'})
# amenities2=amenities2.sort_values(by=['Quantity'], ascending=False)
# amenities2.shape

In [ ]:
#The DataFrame listings_ams has 6517 rows. 
#amenities2=amenities2[amenities2['Quantity']> 200]

In [ ]:
#amenities2

In [ ]:
#amenities2[amenities2['Quantity']> 3260]

In [ ]:
#Check if the rows in the column listings_ams['amenities'] have duplicates
def has1dup(lst):
    return len(lst)-1 == len(set(lst))

In [ ]:
#They have 1361 duplicates
listings_ams['amenities'].apply(has1dup).value_counts()

In [ ]:
#Removing duplicates
def remove_dupl(x):
    return list(dict.fromkeys(x))

In [ ]:
listings_ams['amenities']=listings_ams['amenities'].apply(remove_dupl)

In [ ]:
#Check if all the duplicates were removed
listings_ams['amenities'].apply(has1dup).value_counts()

In [ ]:
unique_amenities2 = {}

for entry in listings_ams["amenities"]:    
    #s = entry[1:-1]
    #l = [x.replace("\"", "").strip() for x in s.split(",")]
    
    for amenity in entry:
        if amenity not in unique_amenities2:
            unique_amenities2[amenity] = 1
        else:
            unique_amenities2[amenity] += 1

In [ ]:
amenities2=pd.DataFrame.from_dict(unique_amenities2.items())
amenities2=amenities2.rename(columns={0:'Amenity',1:'Quantity'})
amenities2=amenities2.sort_values(by=['Quantity'], ascending=False)
amenities2.head(20)

In [ ]:
#The DataFrame listings_ams has 6517 rows. 
amenities2=amenities2[amenities2['Quantity']> 200]
amenities2

In [ ]:
#80% of all properties
amenities2[amenities2['Quantity']> 5200]

In [ ]:
#50% of all properties
amenities2[(amenities2['Quantity']> 3260) & (amenities2['Quantity'] < 5200)]

In [ ]:
#only 20% of all properties
(amenities2[(amenities2['Quantity']> 1300) & (amenities2['Quantity']< 3260) ])

In [ ]:
#only 10% of all properties
amenities2[(amenities2['Quantity']> 650) & (amenities2['Quantity']< 1300)]

In [ ]:
list_new_columns = ['parking', 'cooking_basics', 'dishwasher', 'tv', 'iron', 'private patio or balcony', 'freezer',
                   'dryer', 'private_entrance', 'microwave','self_check_in', 'pets_allowed','bbq_grill']