In [1]:
import pandas as pd
import numpy as np

In [2]:
listings_ams = pd.read_csv('../data/cleaned/listings_ams.csv', index_col=0)

In [3]:
listings_ams.shape

(6809, 33)

In [4]:
pd.options.display.max_columns = None
display(listings_ams)

,name,description,neighborhood_overview,host_id,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,Somewhere Else,Highlights<br />*Located only 5 minutes from C...,NaN,2594559,NaN,within a day,87%,96%,f,t,Westerpark,52.391140,4.888460,Private room in boat,Private room,2,1.5 baths,1.0,1.0,"[""Bed linens"", ""Dishes and silverware"", ""Hange...",$100.00,2,30,t,248,4.85,4.88,4.83,4.93,4.90,4.78,4.72,f
1,Quiet Garden View Room & Super Fast Wi-Fi,Quiet Garden View Room & Super Fast Wi-Fi<br /...,"Indische Buurt (""Indies Neighborhood"") is a ne...",3159,"Upon arriving in Amsterdam, one can imagine as...",within an hour,100%,100%,t,t,Oostelijk Havengebied - Indische Buurt,52.364350,4.943580,Private room in rental unit,Private room,2,1.5 shared baths,1.0,2.0,"[""Books and reading material"", ""Smoke alarm"", ...",$59.00,3,28,t,314,4.89,4.93,4.99,4.97,4.98,4.69,4.81,f
2,Studio with private bathroom in the centre 1,17th century Dutch townhouse in the heart of t...,Located just in between famous central canals....,59484,+ (Phone number hidden by Airbnb),within an hour,100%,98%,f,t,Centrum-Oost,52.364070,4.893930,Private room in townhouse,Private room,2,1 private bath,1.0,1.0,"[""Smoke alarm"", ""Bed linens"", ""Hangers"", ""Wifi...",$106.00,1,365,t,339,4.44,4.69,4.79,4.63,4.62,4.87,4.49,t
3,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,"Central, quiet, safe, clean and beautiful.",97647,"Marjan works in ""eye"" the dutch filmmuseum, an...",within an hour,100%,100%,t,t,Centrum-West,52.387610,4.891880,Private room in houseboat,Private room,2,1.5 baths,1.0,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",$140.00,2,356,t,243,4.94,4.93,4.95,4.95,4.92,4.89,4.79,t
4,Comfortable double room,<b>The space</b><br />In a monumental house ri...,"Flower market , Leidseplein , Rembrantsplein",124245,Hi,within a few hours,100%,100%,t,t,Centrum-West,52.367750,4.890920,Private room in rental unit,Private room,2,1 shared bath,1.0,1.0,"[""Smoke alarm"", ""Bed linens"", ""Lock on bedroom...",$75.00,2,1825,t,454,4.88,4.93,4.89,4.95,4.94,4.97,4.83,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6804,Romantic Houseboat in the center,Located in the center everything can be walked...,"Redlight district, Waterlooplein market, every...",4184910,"Hello,\r\n\r\nMy name is Lydia and live in Ams...",within a day,80%,88%,t,t,Centrum-Oost,52.368637,4.899096,Private room in boat,Private room,2,1 private bath,1.0,1.0,"[""Smoke alarm"", ""Fire extinguisher"", ""Waterfro...",$165.00,1,1125,t,343,4.76,4.83,4.64,4.86,4.71,4.93,4.59,f
6805,mediterranean ambiance appartment,<b>The space</b><br />If you love Mediterranea...,NaN,4215174,It' s been already more than 20 years that I l...,within a day,100%,0%,f,t,De Baarsjes - Oud-West,52.368840,4.861270,Entire rental unit,Entire home/apt,4,1 bath,2.0,2.0,"[""Kitchen"", ""Wifi"", ""TV"", ""Oven"", ""Hot water"",...",$150.00,4,14,t,18,4.83,4.83,4.67,4.94,5.00,4.67,4.50,f
6806,Charlie + Coco's Apartment,Charlie + Coco are looking forward to welcome ...,NaN,1657181,.,within an hour,100%,83%,f,t,De Pijp - Rivierenbuurt,52.352050,4.902670,Entire rental unit,Entire home/apt,3,1 bath,2.0,2.0,"[""Smoke alarm"", ""Patio or balcony"", ""Coffee ma...",$160.00,3,1124,t,97,4.57,4.66,4.41,4.68,4.71,4.76,4.41,f
6807,Sleeping in a unique ship in the center of A'dam!,Thank you for finding me. I offer you an uniqu...,The Keizerinn BnB is located in one of the old...,4221960,Welcome on my boat!\n\nI'm offering you a won...,within an hour,100%,99%,t,t,Centrum-Oost,52.364760,4.909250,Private room in boat,Private room,2,1 private bath,1.0,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",$125.00,1,30,t,1060,4.93,4.92,4.95,4.97,4.97,4.92,4.81,f
6808,Sunny & Bright 3 bed apt with Roof terrace,"This sunny, spacious, trendy and clean 123m2 ...",NaN,4239235,"A bit about me, I love working hard and fillin...",NaN,NaN,50%,f,t,De Pijp - Rivierenbuurt,52.347250,4.893410,Entire rental unit,Entire home/apt,6,1.5 baths,2.0,2.0,"[""Smoke alarm"", ""BBQ grill"", ""Outdoor dining a...",$249.00,4,21,t,17,4.94,5.00,4.94,5.00,5.00,4.76,4.76,f

In [5]:
listings_ams.columns

Index(['name', 'description', 'neighborhood_overview', 'host_id', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_identity_verified', 'neighbourhood_cleansed',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'has_availability',
       'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable'],
      dtype='object')

In [6]:
listings_ams.dtypes

name                            object
description                     object
neighborhood_overview           object
host_id                          int64
host_about                      object
host_response_time              object
host_response_rate              object
host_acceptance_rate            object
host_is_superhost               object
host_identity_verified          object
neighbourhood_cleansed          object
latitude                       float64
longitude                      float64
property_type                   object
room_type                       object
accommodates                     int64
bathrooms_text                  object
bedrooms                       float64
beds                           float64
amenities                       object
price                           object
minimum_nights                   int64
maximum_nights                   int64
has_availability                object
number_of_reviews                int64
review_scores_rating           float64
review_scores_accuracy         float64
review_scores_cleanliness      float64
review_scores_checkin          float64
review_scores_communication    float64
review_scores_location         float64
review_scores_value            float64
instant_bookable                object
dtype: object

In [7]:
listings_ams['host_is_superhost'].unique()

array(['f', 't', nan], dtype=object)

In [8]:
listings_ams.isna().sum()

name                              0
description                       8
neighborhood_overview          2381
host_id                           0
host_about                     2787
host_response_time             2054
host_response_rate             2054
host_acceptance_rate            992
host_is_superhost                 4
host_identity_verified            0
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms_text                   13
bedrooms                        286
beds                             91
amenities                         0
price                             0
minimum_nights                    0
maximum_nights                    0
has_availability                  0
number_of_reviews                 0
review_scores_rating            648
review_scores_accuracy          652
review_scores_cleanliness       652
review_scores_checkin           652
review_scores_communication     652
review_scores_location          652
review_scores_value             652
instant_bookable                  0
dtype: int64

In [9]:
reviews=listings_ams.loc[:,['host_id','review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value']]
reviews.to_csv('../data/cleaned/reviews.csv')

In [10]:
#Dealing with missing values
#deleting host_about column
listings_ams=listings_ams.drop(['host_about','neighborhood_overview','host_response_time',
                                'host_response_rate', 'review_scores_rating', 'review_scores_accuracy',
                                'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication',
                                'review_scores_location', 'review_scores_value', 'host_acceptance_rate',
                                'description'],axis=1)

In [11]:
listings_ams.isna().sum()

name                        0
host_id                     0
host_is_superhost           4
host_identity_verified      0
neighbourhood_cleansed      0
latitude                    0
longitude                   0
property_type               0
room_type                   0
accommodates                0
bathrooms_text             13
bedrooms                  286
beds                       91
amenities                   0
price                       0
minimum_nights              0
maximum_nights              0
has_availability            0
number_of_reviews           0
instant_bookable            0
dtype: int64

In [12]:
#Number of bedrooms is an important information for analysis. Therefore, I decided to delete the rows.
listings_ams=listings_ams[listings_ams['bedrooms'].notna()]

In [13]:
listings_ams.isna().sum()

name                       0
host_id                    0
host_is_superhost          0
host_identity_verified     0
neighbourhood_cleansed     0
latitude                   0
longitude                  0
property_type              0
room_type                  0
accommodates               0
bathrooms_text             6
bedrooms                   0
beds                      72
amenities                  0
price                      0
minimum_nights             0
maximum_nights             0
has_availability           0
number_of_reviews          0
instant_bookable           0
dtype: int64

In [14]:
#Number of bathrooms is an important information for analysis. Therefore, I decided to delete the rows.

listings_ams=listings_ams[listings_ams['bathrooms_text'].notna()]

In [15]:
listings_ams.isna().sum()

name                       0
host_id                    0
host_is_superhost          0
host_identity_verified     0
neighbourhood_cleansed     0
latitude                   0
longitude                  0
property_type              0
room_type                  0
accommodates               0
bathrooms_text             0
bedrooms                   0
beds                      72
amenities                  0
price                      0
minimum_nights             0
maximum_nights             0
has_availability           0
number_of_reviews          0
instant_bookable           0
dtype: int64

In [16]:
#Although the number of beds is important, accommodates indicate the max number of people that the property can host.
#Therefore, I decided to delete the column beds
listings_ams=listings_ams.drop(['beds'], axis=1)

In [17]:
listings_ams.isna().sum()

name                      0
host_id                   0
host_is_superhost         0
host_identity_verified    0
neighbourhood_cleansed    0
latitude                  0
longitude                 0
property_type             0
room_type                 0
accommodates              0
bathrooms_text            0
bedrooms                  0
amenities                 0
price                     0
minimum_nights            0
maximum_nights            0
has_availability          0
number_of_reviews         0
instant_bookable          0
dtype: int64

In [18]:
listings_ams.head()

,name,host_id,host_is_superhost,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,amenities,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,instant_bookable
0,Somewhere Else,2594559,f,t,Westerpark,52.39114,4.88846,Private room in boat,Private room,2,1.5 baths,1.0,"[""Bed linens"", ""Dishes and silverware"", ""Hange...",$100.00,2,30,t,248,f
1,Quiet Garden View Room & Super Fast Wi-Fi,3159,t,t,Oostelijk Havengebied - Indische Buurt,52.36435,4.94358,Private room in rental unit,Private room,2,1.5 shared baths,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",$59.00,3,28,t,314,f
2,Studio with private bathroom in the centre 1,59484,f,t,Centrum-Oost,52.36407,4.89393,Private room in townhouse,Private room,2,1 private bath,1.0,"[""Smoke alarm"", ""Bed linens"", ""Hangers"", ""Wifi...",$106.00,1,365,t,339,t
3,"Romantic, stylish B&B houseboat in canal district",97647,t,t,Centrum-West,52.38761,4.89188,Private room in houseboat,Private room,2,1.5 baths,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",$140.00,2,356,t,243,t
4,Comfortable double room,124245,t,t,Centrum-West,52.36775,4.89092,Private room in rental unit,Private room,2,1 shared bath,1.0,"[""Smoke alarm"", ""Bed linens"", ""Lock on bedroom...",$75.00,2,1825,t,454,f

In [19]:
#Clean: remove '$' from price
def remove_symbol(x):
    x=x.replace('$','')
    return x


def remove_symbol_2(x):
    x=x.replace(',','')
    return x


listings_ams['price']=listings_ams['price'].apply(remove_symbol)
listings_ams['price']=listings_ams['price'].apply(remove_symbol_2)

In [20]:
listings_ams['bathrooms_text'].unique()

array(['1.5 baths', '1.5 shared baths', '1 private bath', '1 shared bath',
       '1 bath', '2.5 baths', '3.5 baths', '0 baths', 'Private half-bath',
       '2 baths', '3 baths', '0 shared baths', 'Half-bath', '5 baths',
       'Shared half-bath', '2 shared baths', '5.5 baths', '4 baths',
       '4.5 baths', '4 shared baths', '17 baths', '3 shared baths'],
      dtype=object)

In [21]:
listings_ams.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6517 entries, 0 to 6808
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    6517 non-null   object
 1   host_id                 6517 non-null   int64
 2   host_is_superhost       6517 non-null   object
 3   host_identity_verified  6517 non-null   object
 4   neighbourhood_cleansed  6517 non-null   object
 5   latitude                6517 non-null   float64
 6   longitude               6517 non-null   float64
 7   property_type           6517 non-null   object
 8   room_type               6517 non-null   object
 9   accommodates            6517 non-null   int64
 10  bathrooms_text          6517 non-null   object
 11  bedrooms                6517 non-null   float64
 12  amenities               6517 non-null   object
 13  price                   6517 non-null   object
 14  minimum_nights          6517 non-null   int64
 15  maximum_nights          6517 non-null   int64
 16  has_availability        6517 non-null   object
 17  number_of_reviews       6517 non-null   int64
 18  instant_bookable        6517 non-null   object
dtypes: float64(3), int64(5), object(11)
memory usage: 1018.3+ KB

In [22]:
#Transform data type

#'bedrooms' - int
listings_ams['bedrooms'].astype(int)

0       1
1       1
2       1
3       1
4       1
       ..
6804    1
6805    2
6806    2
6807    1
6808    2
Name: bedrooms, Length: 6517, dtype: int64

In [23]:
#'price' - int

listings_ams['price']=listings_ams['price'].astype(float)

In [24]:
listings_ams.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6517 entries, 0 to 6808
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    6517 non-null   object
 1   host_id                 6517 non-null   int64
 2   host_is_superhost       6517 non-null   object
 3   host_identity_verified  6517 non-null   object
 4   neighbourhood_cleansed  6517 non-null   object
 5   latitude                6517 non-null   float64
 6   longitude               6517 non-null   float64
 7   property_type           6517 non-null   object
 8   room_type               6517 non-null   object
 9   accommodates            6517 non-null   int64
 10  bathrooms_text          6517 non-null   object
 11  bedrooms                6517 non-null   float64
 12  amenities               6517 non-null   object
 13  price                   6517 non-null   float64
 14  minimum_nights          6517 non-null   int64
 15  maximum_nights          6517 non-null   int64
 16  has_availability        6517 non-null   object
 17  number_of_reviews       6517 non-null   int64
 18  instant_bookable        6517 non-null   object
dtypes: float64(4), int64(5), object(10)
memory usage: 1018.3+ KB

In [25]:
listings_ams.to_csv('../data/cleaned/listings_ams2.csv')

In [26]:
pd.options.display.max_columns = None
display(listings_ams)

,name,host_id,host_is_superhost,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,amenities,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,instant_bookable
0,Somewhere Else,2594559,f,t,Westerpark,52.391140,4.888460,Private room in boat,Private room,2,1.5 baths,1.0,"[""Bed linens"", ""Dishes and silverware"", ""Hange...",100.0,2,30,t,248,f
1,Quiet Garden View Room & Super Fast Wi-Fi,3159,t,t,Oostelijk Havengebied - Indische Buurt,52.364350,4.943580,Private room in rental unit,Private room,2,1.5 shared baths,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",59.0,3,28,t,314,f
2,Studio with private bathroom in the centre 1,59484,f,t,Centrum-Oost,52.364070,4.893930,Private room in townhouse,Private room,2,1 private bath,1.0,"[""Smoke alarm"", ""Bed linens"", ""Hangers"", ""Wifi...",106.0,1,365,t,339,t
3,"Romantic, stylish B&B houseboat in canal district",97647,t,t,Centrum-West,52.387610,4.891880,Private room in houseboat,Private room,2,1.5 baths,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",140.0,2,356,t,243,t
4,Comfortable double room,124245,t,t,Centrum-West,52.367750,4.890920,Private room in rental unit,Private room,2,1 shared bath,1.0,"[""Smoke alarm"", ""Bed linens"", ""Lock on bedroom...",75.0,2,1825,t,454,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6804,Romantic Houseboat in the center,4184910,t,t,Centrum-Oost,52.368637,4.899096,Private room in boat,Private room,2,1 private bath,1.0,"[""Smoke alarm"", ""Fire extinguisher"", ""Waterfro...",165.0,1,1125,t,343,f
6805,mediterranean ambiance appartment,4215174,f,t,De Baarsjes - Oud-West,52.368840,4.861270,Entire rental unit,Entire home/apt,4,1 bath,2.0,"[""Kitchen"", ""Wifi"", ""TV"", ""Oven"", ""Hot water"",...",150.0,4,14,t,18,f
6806,Charlie + Coco's Apartment,1657181,f,t,De Pijp - Rivierenbuurt,52.352050,4.902670,Entire rental unit,Entire home/apt,3,1 bath,2.0,"[""Smoke alarm"", ""Patio or balcony"", ""Coffee ma...",160.0,3,1124,t,97,f
6807,Sleeping in a unique ship in the center of A'dam!,4221960,t,t,Centrum-Oost,52.364760,4.909250,Private room in boat,Private room,2,1 private bath,1.0,"[""Books and reading material"", ""Smoke alarm"", ...",125.0,1,30,t,1060,f
6808,Sunny & Bright 3 bed apt with Roof terrace,4239235,f,t,De Pijp - Rivierenbuurt,52.347250,4.893410,Entire rental unit,Entire home/apt,6,1.5 baths,2.0,"[""Smoke alarm"", ""BBQ grill"", ""Outdoor dining a...",249.0,4,21,t,17,f

In [27]:
listings_ams['amenities'][1]

'["Books and reading material", "Smoke alarm", "Fire extinguisher", "Dedicated workspace", "Paid parking off premises", "Room-darkening shades", "Paid washer \\u2013 In unit", "Bed linens", "Private entrance", "Outdoor furniture", "Fast wifi \\u2013 52 Mbps", "Security cameras on property", "Mini fridge", "Essentials", "Ethernet connection", "Sony + Wireless Bluetooth Speaker(phone) Bluetooth sound system", "Central heating", "Cleaning products", "First aid kit", "Carbon monoxide alarm", "Paid parking on premises", "Extra pillows and blankets", "PH neutral and dermatologically tested shampoo", "Hot water kettle", "Clothing storage: wardrobe", "Single level home", "Portable fans", "Garden view", "Hair dryer", "Hot water", "Lock on bedroom door", "Host greets you", "Hangers", "Laundromat nearby", "Long term stays allowed", "Coffee", "Iron", "PH neutral and dermatologically tested body soap", "Drying rack for clothing", "Exercise equipment: yoga mat", "Shared backyard \\u2013 Fully fenced", "Shower gel", "Refrigerator", "Mosquito net"]'

In [28]:
listings_ams['amenities'][2]

'["Smoke alarm", "Bed linens", "Hangers", "Wifi", "Fire extinguisher", "Long term stays allowed", "Essentials", "TV", "Hair dryer", "Hot water", "Paid parking off premises", "Host greets you", "Free street parking", "Refrigerator", "Carbon monoxide alarm", "Heating"]'

In [29]:
listings_ams['amenities'][3]

'["Books and reading material", "Smoke alarm", "Smart lock", "Fire extinguisher", "Dedicated workspace", "Waterfront", "Luggage dropoff allowed", "Bikes", "Self check-in", "Boat slip", "City skyline view", "Private patio or balcony", "Bed linens", "Paid street parking off premises", "Hp neutral, eco friendly body soap", "Private entrance", "Outdoor furniture", "Breakfast", "Kayak", "Private living room", "Mini fridge", "Essentials", "Public or shared beach access", "Central heating", "Lake access", "Outdoor dining area", "Coffee maker: Nespresso", "Carbon monoxide alarm", "Extra pillows and blankets", "Harbor view", "Portable fans", "Shampoo", "Garden view", "Fast wifi \\u2013 245 Mbps", "Private backyard \\u2013 Not fully fenced", "Hair dryer", "Hot water", "Lock on bedroom door", "Dishes and silverware", "Safe", "Wine glasses", "Hangers", "Canal view", "Dining table", "Laundromat nearby", "Long term stays allowed", "Coffee", "Clothing storage: closet", "TV with standard cable", "Shower gel", "Refrigerator"]'

In [30]:
listings_ams.shape

(6517, 19)

In [31]:
#Code for getting all the amenities listed in the listings_ams['amenities']


# unique_amenities = {}

# for entry in listings_ams["amenities"]:    
#     s = entry[1:-1]
#     l = [x.replace("\"", "").strip() for x in s.split(",")]
    
#     for amenity in l:
#         if amenity not in unique_amenities:
#             unique_amenities[amenity] = 1
#         else:
#             unique_amenities[amenity] += 1
            
            
# unique_amenities            

# top20_amenities = sorted(unique_amenities.items(), key=lambda x: x[1])[-20:]
# top20_amenities = [x[0] for x in top20_amenities]
# top20_amenities

In [32]:
# amenities=pd.DataFrame.from_dict(unique_amenities.items())
# amenities=amenities.rename(columns={0:'Amenity',1:'Quantity'})
# amenities=amenities.sort_values(by=['Quantity'], ascending=False)
# amenities.tail(50)

In [33]:
type(listings_ams['amenities'][3])

str


Smoke_Alarm median_price_1 
Essentials median_price_2
Wifi median_price_3

In [34]:
def clean5 (l):
    l = l.split(",")
    l = ["TV" if "TV" in x else x for x in l]
    l = ["Sound System" if "sound system" in x else x for x in l]
    l = ["Shampoo" if "shampoo" in x else x for x in l]
    l = ["Shampoo" if "Shampoo" in x else x for x in l]
    l = ["Shower gel" if "soap" in x else x for x in l]
    l = ["Shower gel" if "Shower gel" in x else x for x in l]
    l = ["Conditioner" if "conditioner" in x else x for x in l]
    l = ["Conditioner" if "Conditioner" in x else x for x in l]
    l = ["Wifi" if "Wifi" in x else x for x in l]
    l = ["Wifi" if "Mbps" in x else x for x in l]
    l = ["Wifi" if "Mbps" in x else x for x in l]
    l = ["Stove" if "stove" in x else x for x in l]
    l = ["Oven" if "oven" in x else x for x in l]
    l = ["Refrigerator" if "refrigerator" in x else x for x in l]
    l = ["Wardrobe" if "wardrobe" in x else x for x in l]
    l = ["Closet" if "closet" in x else x for x in l]
    l = ["Paid parking" if "Paid parking" in x else x for x in l]
    l = ["High chair" if "high chair" in x else x for x in l]
    l = ["Coffee maker" if "Coffee maker" in x else x for x in l]
    l = ["Hot tub" if "hot tub" in x else x for x in l]
    l = ["Coffee maker" if "Nespresso" in x else x for x in l]
    l = ["Wardrobe" if "dresser" in x else x for x in l]
    l = ["Kitchen" if "kitchen" in x else x for x in l]
    l = ["Kitchen" if "Kitchen" in x else x for x in l]
    l = ["Fireplace" if "fireplace" in x else x for x in l]
    l = ["Coffee" if "pour-over coffee" in x else x for x in l]
    l = ["Bed linen" if "Bed linens" in x else x for x in l]
    l = ["Coffee" if "Coffee" in x else x for x in l]
    l = ["Crib" if "Crib" in x else x for x in l]
    l = ["Bike" if "Bikes" in x else x for x in l]
    l = ["Bike" if "bike" in x else x for x in l]
    l = ["Elevator" if "Lift" in x else x for x in l]
    l = ["Netflix" if "Netflix" in x else x for x in l]
    l = ["Central heating" if "Heating" in x else x for x in l]
    l = ["Free washer" if "Free washer" in x else x for x in l]
    l = ["Free dryer" if "Free dryer" in x else x for x in l]
    l = ["Children books and toys" if "books and toys" in x else x for x in l]
    l = ["Wardrobe" if "Clothing storage" in x else x for x in l]
    l = ["Fireplace" if "Fire pit" in x else x for x in l]
    l = ["Backyard" if "backyard" in x else x for x in l]
    l = ["Backyard" if "Backyard" in x else x for x in l]
    l = ["Backyard" if "backyard" in x else x for x in l]
    l = ["Parking" if "parking" in x else x for x in l]
    l = ["Parking" if "Parking" in x else x for x in l]
    l = ["Air conditioning" if "air conditioning" in x else x for x in l]
    l = ["Air conditioning" if "Air conditioning" in x else x for x in l]

    return l

In [35]:
listings_ams['amenities']=listings_ams['amenities'].apply(clean5)

In [36]:
listings_ams['amenities'][3]

['["Books and reading material"',
 ' "Smoke alarm"',
 ' "Smart lock"',
 ' "Fire extinguisher"',
 ' "Dedicated workspace"',
 ' "Waterfront"',
 ' "Luggage dropoff allowed"',
 'Bike',
 ' "Self check-in"',
 ' "Boat slip"',
 ' "City skyline view"',
 ' "Private patio or balcony"',
 'Bed linen',
 'Parking',
 ' "Hp neutral',
 'Shower gel',
 ' "Private entrance"',
 ' "Outdoor furniture"',
 ' "Breakfast"',
 ' "Kayak"',
 ' "Private living room"',
 ' "Mini fridge"',
 ' "Essentials"',
 ' "Public or shared beach access"',
 ' "Central heating"',
 ' "Lake access"',
 ' "Outdoor dining area"',
 'Coffee',
 ' "Carbon monoxide alarm"',
 ' "Extra pillows and blankets"',
 ' "Harbor view"',
 ' "Portable fans"',
 'Shampoo',
 ' "Garden view"',
 'Wifi',
 'Backyard',
 ' "Hair dryer"',
 ' "Hot water"',
 ' "Lock on bedroom door"',
 ' "Dishes and silverware"',
 ' "Safe"',
 ' "Wine glasses"',
 ' "Hangers"',
 ' "Canal view"',
 ' "Dining table"',
 ' "Laundromat nearby"',
 ' "Long term stays allowed"',
 'Coffee',
 'Closet',
 'TV',
 'Shower gel',
 ' "Refrigerator"]']

In [37]:
pd.options.display.max_columns = None
display(listings_ams)

,name,host_id,host_is_superhost,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,amenities,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,instant_bookable
0,Somewhere Else,2594559,f,t,Westerpark,52.391140,4.888460,Private room in boat,Private room,2,1.5 baths,1.0,"[Bed linen, ""Dishes and silverware"", ""Hanger...",100.0,2,30,t,248,f
1,Quiet Garden View Room & Super Fast Wi-Fi,3159,t,t,Oostelijk Havengebied - Indische Buurt,52.364350,4.943580,Private room in rental unit,Private room,2,1.5 shared baths,1.0,"[[""Books and reading material"", ""Smoke alarm""...",59.0,3,28,t,314,f
2,Studio with private bathroom in the centre 1,59484,f,t,Centrum-Oost,52.364070,4.893930,Private room in townhouse,Private room,2,1 private bath,1.0,"[[""Smoke alarm"", Bed linen, ""Hangers"", Wifi, ...",106.0,1,365,t,339,t
3,"Romantic, stylish B&B houseboat in canal district",97647,t,t,Centrum-West,52.387610,4.891880,Private room in houseboat,Private room,2,1.5 baths,1.0,"[[""Books and reading material"", ""Smoke alarm""...",140.0,2,356,t,243,t
4,Comfortable double room,124245,t,t,Centrum-West,52.367750,4.890920,Private room in rental unit,Private room,2,1 shared bath,1.0,"[[""Smoke alarm"", Bed linen, ""Lock on bedroom ...",75.0,2,1825,t,454,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6804,Romantic Houseboat in the center,4184910,t,t,Centrum-Oost,52.368637,4.899096,Private room in boat,Private room,2,1 private bath,1.0,"[[""Smoke alarm"", ""Fire extinguisher"", ""Water...",165.0,1,1125,t,343,f
6805,mediterranean ambiance appartment,4215174,f,t,De Baarsjes - Oud-West,52.368840,4.861270,Entire rental unit,Entire home/apt,4,1 bath,2.0,"[Kitchen, Wifi, TV, ""Oven"", ""Hot water"", ""D...",150.0,4,14,t,18,f
6806,Charlie + Coco's Apartment,1657181,f,t,De Pijp - Rivierenbuurt,52.352050,4.902670,Entire rental unit,Entire home/apt,3,1 bath,2.0,"[[""Smoke alarm"", ""Patio or balcony"", Coffee, ...",160.0,3,1124,t,97,f
6807,Sleeping in a unique ship in the center of A'dam!,4221960,t,t,Centrum-Oost,52.364760,4.909250,Private room in boat,Private room,2,1 private bath,1.0,"[[""Books and reading material"", ""Smoke alarm""...",125.0,1,30,t,1060,f
6808,Sunny & Bright 3 bed apt with Roof terrace,4239235,f,t,De Pijp - Rivierenbuurt,52.347250,4.893410,Entire rental unit,Entire home/apt,6,1.5 baths,2.0,"[[""Smoke alarm"", ""BBQ grill"", ""Outdoor dinin...",249.0,4,21,t,17,f

In [38]:
# unique_amenities2 = {}

# for entry in listings_ams["amenities"]:    
# #     s = entry[1:-1]
# #     l = [x.replace("\"", "").strip() for x in s.split(",")]
    
#     for amenity in entry:
#         if amenity not in unique_amenities2:
#             unique_amenities2[amenity] = 1
#         else:
#             unique_amenities2[amenity] += 1

In [39]:
# amenities2=pd.DataFrame.from_dict(unique_amenities2.items())
# amenities2=amenities2.rename(columns={0:'Amenity',1:'Quantity'})
# amenities2=amenities2.sort_values(by=['Quantity'], ascending=False)
# amenities2.shape

In [40]:
#The DataFrame listings_ams has 6517 rows. 
#amenities2=amenities2[amenities2['Quantity']> 200]

In [41]:
#amenities2

In [42]:
#amenities2[amenities2['Quantity']> 3260]

In [43]:
#Check if the rows in the column listings_ams['amenities'] have duplicates
def has1dup(lst):
    return len(lst)-1 == len(set(lst))

In [44]:
#They have 1361 duplicates
listings_ams['amenities'].apply(has1dup).value_counts()

False    5190
True     1327
Name: amenities, dtype: int64

In [45]:
#Removing duplicates
def remove_dupl(x):
    return list(dict.fromkeys(x))

In [46]:
listings_ams['amenities']=listings_ams['amenities'].apply(remove_dupl)

In [47]:
#Check if all the duplicates were removed
listings_ams['amenities'].apply(has1dup).value_counts()

False    6517
Name: amenities, dtype: int64

In [48]:
unique_amenities2 = {}

for entry in listings_ams["amenities"]:    
    #s = entry[1:-1]
    #l = [x.replace("\"", "").strip() for x in s.split(",")]
    
    for amenity in entry:
        if amenity not in unique_amenities2:
            unique_amenities2[amenity] = 1
        else:
            unique_amenities2[amenity] += 1

In [49]:
amenities2=pd.DataFrame.from_dict(unique_amenities2.items())
amenities2=amenities2.rename(columns={0:'Amenity',1:'Quantity'})
amenities2=amenities2.sort_values(by=['Quantity'], ascending=False)
amenities2.head

                       Amenity  Quantity
3                         Wifi      6406
11                "Essentials"      5797
81                     Kitchen      5342
51                          TV      5103
14                 "Hot water"      4944
1      "Dishes and silverware"      4824
41                "Hair dryer"      4805
43                      Coffee      4702
2                    "Hangers"      4667
8    "Long term stays allowed"      4652
44                      "Iron"      4484
18             Central heating      4462
50              ["Smoke alarm"      4227
0                    Bed linen      4165
9                      Shampoo      4147
80            "Cooking basics"      4035
23                     Parking      3809
34     "Carbon monoxide alarm"      3414
78                    "Washer"      3357
75                "Dishwasher"      3267

In [56]:
amenities2.to_csv('../data/cleaned/amenities.csv')

In [50]:
#The DataFrame listings_ams has 6517 rows. 
amenities2=amenities2[amenities2['Quantity']> 200]
amenities2

                        Amenity  Quantity
3                          Wifi      6406
11                 "Essentials"      5797
81                      Kitchen      5342
51                           TV      5103
14                  "Hot water"      4944
..                          ...       ...
96                 Refrigerator       221
116             standard cable"       219
49              "Mosquito net"]       204
129   "Shared patio or balcony"       204
118         "Baby safety gates"       201

[107 rows x 2 columns]

In [51]:
#80% of all properties
amenities2[amenities2['Quantity']> 5200]

          Amenity  Quantity
3            Wifi      6406
11   "Essentials"      5797
81        Kitchen      5342

In [52]:
#50% of all properties
amenities2[(amenities2['Quantity']> 3260) & (amenities2['Quantity'] < 5200)]

                       Amenity  Quantity
51                          TV      5103
14                 "Hot water"      4944
1      "Dishes and silverware"      4824
41                "Hair dryer"      4805
43                      Coffee      4702
2                    "Hangers"      4667
8    "Long term stays allowed"      4652
44                      "Iron"      4484
18             Central heating      4462
50              ["Smoke alarm"      4227
0                    Bed linen      4165
9                      Shampoo      4147
80            "Cooking basics"      4035
23                     Parking      3809
34     "Carbon monoxide alarm"      3414
78                    "Washer"      3357
75                "Dishwasher"      3267

In [53]:
#only 20% of all properties
(amenities2[(amenities2['Quantity']> 1300) & (amenities2['Quantity']< 3260) ])

                          Amenity  Quantity
4             "Fire extinguisher"      3258
33                "First aid kit"      2981
71                "Refrigerator"]      2960
76                         "Oven"      2933
5                     "Microwave"      2909
6              "Private entrance"      2905
22          "Dedicated workspace"      2826
74                        "Stove"      2429
45                     Shower gel      2355
32            "Cleaning products"      2344
35   "Extra pillows and blankets"      2208
69                 "Dining table"      2167
67                 "Wine glasses"      2154
36             "Hot water kettle"      2080
92                      "Freezer"      1887
13      "Luggage dropoff allowed"      1869
16              "Host greets you"      1847
57     "Private patio or balcony"      1803
72                        "Dryer"      1648
26            "Outdoor furniture"      1644
17                 "Refrigerator"      1623
46     "Drying rack for clothing"      1604
21                  "Smoke alarm"      1596
86                      "Bathtub"      1463
24        "Room-darkening shades"      1455
64          "Outdoor dining area"      1424
48                       Backyard      1419
31              "Central heating"      1329

In [54]:
#only 10% of all properties
amenities2[(amenities2['Quantity']> 650) & (amenities2['Quantity']< 1300)]

                           Amenity  Quantity
42             "Laundromat nearby"      1276
104                    Free washer      1273
54                 "Self check-in"      1216
90                       "Toaster"      1168
20   ["Books and reading material"      1147
105                     Free dryer      1126
37                        Wardrobe      1123
12                    "Waterfront"      1092
39                 "Portable fans"      1057
89                     Conditioner      1026
77              "Patio or balcony"      1012
38             "Single level home"       956
15          "Lock on bedroom door"       939
106                      "Blender"       936
130                 "Baking sheet"       926
85         Children books and toys       924
99                       "Lockbox"       894
112                          Stove       870
107                    "BBQ grill"       829
70                          Closet       815
68                    "Canal view"       785
73                  "Pets allowed"       772
29           "Ethernet connection"       755
83                   "Board games"       746
79                Air conditioning       731
30                    Sound System       725
40                   "Garden view"       722
91                    "High chair"       651

In [55]:
list_new_columns = ['parking', 'cooking_basics', 'dishwasher', 'tv', 'iron', 'private patio or balcony', 'freezer',
                   'dryer', 'private_entrance', 'microwave','self_check_in', 'pets_allowed','bbq_grill']